### ISSUE TITLE
Update info

### ISSUE THREAD

**Issue by jeferbc** [jeferbc/jeferbc.github.io#1]
1) Edad, ya tengo 28 años
2) Subir porcentaje de habilidades de la siguiente forma:
   *  Ruby on Rails: 100%
   * HTML5 y CSS3: 100%
   * Javascript / Coffeescript: 90%
   * ReactJS: 70%
   * Jquery and Ajax: 90%
   * Rest API: 100%
   * Testing: 100%
   * Git and Github: 100%
3) Agregar una nueva grafica con el texto: "NodeJS / Express": 60%
4) Cambiar la fecha del footer a 2018

**Comment by 56kz** [comment]
1.Edad 28
2.Listo
3.Listo
4. R
